[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "osmosis"
version = "0.1.0"
description = "OpenStudio wrapper library"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]